---

- command: "image"
  subcommand: "list"
  name: "List docker images"
  description: "List docker image available on the docker host."
  exec: 
    - scripts/docker/image_list.sh
  response:
    type: "ephemeral"
    template: |
      | Repository | Tag | ID | Created | Size |
      |---|---|---|---|---|
      {{range $i, $a := .Data -}}
      | {{ $a.Repository }} | {{ $a.Tag }} | {{ $a.ID }} | {{ $a.CreatedAt }}| {{ $a.Size }} |
      {{end}}

...