---

- command: "inspect"
  name: "Inspect docker container"
  description: "Inspect docker container. Usage `docker inspect [container_id]`"
  exec: 
    - scripts/docker/inspect.sh
  response:
    type: "ephemeral"
    template: |
      ```yml
      {{toHTMLUnescapedYaml .Data}}
      ```

...