---

- command: "ps"
  name: "List docker containers"
  description: "List running docker containers on the docker host. With `-a` flag it will list all docker containers"
  exec: 
    - scripts/docker/ps.sh
  response:
    type: "ephemeral"
    template: |
      | Container ID | Image | Command | Created | Status | Ports | Names |
      |---|---|---|---|---|---|---|
      {{range $i, $a := .Data -}}
      | {{ $a.ID }} | {{ $a.Image }} | {{ $a.Command }} | {{ $a.CreatedAt }} | {{ $a.Status }} | {{ $a.Ports }} | {{ $a.Names }} |
      {{end}}

...