---

- command: "docker ps"
  name: "List running docker containers"
  description: "List running docker contains on the docker host."
  exec: 
    - scripts/docker/ps.sh
  response:
    type: "ephemeral"
    template: |
      | Container ID | Image | Command | Created | Status | Ports | Names |
      |---|---|---|---|---|---|---|
      {{range $i, $a := .Data -}}
      | {{ $a.ID }} | {{ $a.Image }} | {{ $a.Command }} | {{ $a.CreatedAt }} | {{ $a.Status }} | {{ $a.Ports }} | {{ $a.Names }} |
      {{end}}

- command: "docker ps all"
  name: "List all docker containers"
  description: "List all docker contains on the docker host."
  exec: 
    - scripts/docker/ps.sh
  vars:
    - name: DOCKER_PS_FLAGS
      value: "-a"
  response:
    type: "ephemeral"
    template: |
      | Container ID | Image | Command | Created | Status | Ports | Names |
      |---|---|---|---|---|---|---|
      {{range $i, $a := .Data -}}
      | {{ $a.ID }} | {{ $a.Image }} | {{ $a.Command }} | {{ $a.CreatedAt }} | {{ $a.Status }} | {{ $a.Ports }} | {{ $a.Names }} |
      {{end}}
...