---

listen: "{{ .Env.MM_OPTOOLS_LISTEN }}"
base_url: "https://op-tools-address.com"
plugins:
  - name: bash_useful
    file: dist/plugins/bash.so
    config:
      files:
        - commands/gitlab/gitlab.yaml
        - commands/docker/docker.yaml
        - commands/k8s/k8s.yaml
        - commands/release/release.yaml
  - name: bash_fun
    file: dist/plugins/bash.so
    config:
      files:
        - commands/helloworld/helloworld.yaml
        - commands/fun/fun.yaml    
commands: 
  - command: jops
    plugins:
      - name: bash_useful
      - name: bash_fun
        exclude: ["fun figlet"]
      - name: bash_fun
        only: ["fun figlet"]
    token: "MATTERMOST_SLASHCOMMAND_TOKEN"
    dialog_url: https://my-mattermost-instance.cloud.mattermost.com/api/v4/actions/dialogs/open
    dialog_response_url: https://my-mattermost-instance.cloud.mattermost.com/hooks/random-id
    scheduler_response_url:  https://my-mattermost-instance.cloud.mattermost.com/hooks/random-id
    access_control:
      team_name: ["team-name"]
      channel_id: ["channel-id"]
      user_name: ["user1", "user2"]
scheduler:
  - name: "Check Gitlab Version"
    command: "jops gitlab version --check"
    channel: "ops-tool-notifications"
    cron: "0 * * * *"
  - name: "Joke"
    channel: "fun"
    command: "jops fun joke"
    cron: "*/5 * * * *"
  - name: "Fortune"
    channel: "fun"
    command: "jops fun fortune"
    cron: "*/6 * * *"
    
...

