---

listen: "0.0.0.0:8080"
token: "TOKEN"
commands:
  - commands/gitlab/gitlab.yaml
  - commands/docker/docker.yaml
  - commands/fun/fun.yaml
scheduler:
  - name: "Check Gitlab Version"
    command: "gitlab upgrade check"
    cron: "0 10 * * *"
    hook: "MM_INCOMING_HOOK_URL"

...