---

listen: "0.0.0.0:8080"
token: "TOKEN"
commands:
  - commands/gitlab/gitlab.yaml
  - commands/docker/docker.yaml
  - commands/fun/fun.yaml
scheduler:
  - name: "Check Gitlab Version"
    provider: "gitlab"
    command: "version"
    args:
      - "check"
    cron: "0 * * * *"
    hook: "HOOK"
  - name: "Joke"
    provider: "fun"
    command: "joke"
    cron: "*/5 * * * *"
    hook: "HOOK"
  - name: "Fortune"
    provider: "fun"
    command: "fortune"
    cron: "*/15 * * *"
    hook: "HOOK"    

...